# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 06:44
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group


def add_group(apps, schema_editor):
	group, created = Group.objects.get_or_create(name='professor')
	group, created = Group.objects.get_or_create(name='student')
	group, created = Group.objects.get_or_create(name='sys_admin')

class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(add_group),
    ]
